### PR TITLE
table component ui improvement

### PR DESCRIPTION
**Pull request by meenakshi-ss**
- Removed Hover effect on Table Header and changed the bg
- Added only borderBottom
- Updated hover and active colors for Tr 
- Added pointer cursor type for row elements 
- Added docs for Table component

### CODE REVIEW

**Comment by justin-ss** [comment]
@meenakshi-ss  we don't have a documentation on Table Component. It would be nice to release that also. @akzhysparrow   please coordinate on what all has to be documented

**Comment by akzhysparrow** [comment]
@justin-ss There is a an issue with table in docusaurus, the default styling for tables in docusaurus is interfering with the styles that we are applying and the output is incorrect. We will either have to force reset all the styles for docs alone or we will have to embed it in an iframe. 
I tried using shadow DOM but in that case stitches styles were also not getting applied.

**Comment by justin-ss** [comment]
> @justin-ss There is a an issue with table in docusaurus, the default styling for tables in docusaurus is interfering with the styles that we are applying and the output is incorrect. We will either have to force reset all the styles for docs alone or we will have to embed it in an iframe. I tried using shadow DOM but in that case stitches styles were also not getting applied.

Is this a problem in Live Editor also?

**Comment by meenakshi-ss** [comment]
> > @justin-ss There is a an issue with table in docusaurus, the default styling for tables in docusaurus is interfering with the styles that we are applying and the output is incorrect. We will either have to force reset all the styles for docs alone or we will have to embed it in an iframe. I tried using shadow DOM but in that case stitches styles were also not getting applied.
> 
> Is this a problem in Live Editor also?

@justin-ss , the issue is happening in live editor and its preview only, and in storybook it is working fine.

**Comment by akzhysparrow** [comment]
We could make a sandbox and link it there instead of live preview until the playground can support custom examples @justin-ss

**Review by akzhysparrow — APPROVED** [review]

**Review by maneeshp97 — APPROVED** [review]

**Comment by maneeshp97** [comment]
@all-contributors please add @meenakshi-ss for code, bug

**Pull request merged**
